//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.10 at 06:38:11 GMT 
//


package hermes.config;


/**
 * Java content class for config element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/work/Workspaces/Hermes/Hermes/src/xml/hermes-schema.xsd line 225)
 * <p>
 * <pre>
 * &lt;element name="config" type="{}HermesConfig"/>
 * </pre>
 * 
 */
public interface Config
    extends javax.xml.bind.Element, hermes.config.HermesConfig
{


}
