//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.27 at 12:37:15 BST 
//


package hermes.config;


/**
 * Java content class for NamingConfig complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/work/Workspaces/Hermes/HermesJMS/src/xml/hermes-schema.xsd line 198)
 * <p>
 * <pre>
 * &lt;complexType name="NamingConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{}PropertySetConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classpathId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NamingConfig {


    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    /**
     * Gets the value of the classpathId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getClasspathId();

    /**
     * Sets the value of the classpathId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setClasspathId(java.lang.String value);

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link hermes.config.PropertySetConfig}
     */
    hermes.config.PropertySetConfig getProperties();

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link hermes.config.PropertySetConfig}
     */
    void setProperties(hermes.config.PropertySetConfig value);

}
