//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.27 at 12:37:15 BST 
//


package hermes.config;


/**
 * Java content class for NamingProviderConfig complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/work/Workspaces/Hermes/HermesJMS/src/xml/hermes-schema.xsd line 208)
 * <p>
 * <pre>
 * &lt;complexType name="NamingProviderConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="namingConfig" type="{}NamingConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="connectionFactoryBinding" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NamingProviderConfig {


    /**
     * Gets the value of the namingConfig property.
     * 
     * @return
     *     possible object is
     *     {@link hermes.config.NamingConfig}
     */
    hermes.config.NamingConfig getNamingConfig();

    /**
     * Sets the value of the namingConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link hermes.config.NamingConfig}
     */
    void setNamingConfig(hermes.config.NamingConfig value);

    /**
     * Gets the value of the connectionFactoryBinding property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getConnectionFactoryBinding();

    /**
     * Sets the value of the connectionFactoryBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setConnectionFactoryBinding(java.lang.String value);

}
