//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.29 at 03:52:48 PM BST 
//


package hermes.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hermes.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hermes.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HermesConfig }
     * 
     */
    public HermesConfig createHermesConfig() {
        return new HermesConfig();
    }

    /**
     * Create an instance of {@link PropertyConfig }
     * 
     */
    public PropertyConfig createPropertyConfig() {
        return new PropertyConfig();
    }

    /**
     * Create an instance of {@link ClasspathConfig }
     * 
     */
    public ClasspathConfig createClasspathConfig() {
        return new ClasspathConfig();
    }

    /**
     * Create an instance of {@link RemoteConfig }
     * 
     */
    public RemoteConfig createRemoteConfig() {
        return new RemoteConfig();
    }

    /**
     * Create an instance of {@link JDBCStore }
     * 
     */
    public JDBCStore createJDBCStore() {
        return new JDBCStore();
    }

    /**
     * Create an instance of {@link ProviderExtConfig }
     * 
     */
    public ProviderExtConfig createProviderExtConfig() {
        return new ProviderExtConfig();
    }

    /**
     * Create an instance of {@link WatchConfig }
     * 
     */
    public WatchConfig createWatchConfig() {
        return new WatchConfig();
    }

    /**
     * Create an instance of {@link ProviderConfig }
     * 
     */
    public ProviderConfig createProviderConfig() {
        return new ProviderConfig();
    }

    /**
     * Create an instance of {@link PropertySetConfig }
     * 
     */
    public PropertySetConfig createPropertySetConfig() {
        return new PropertySetConfig();
    }

    /**
     * Create an instance of {@link DestinationConfig }
     * 
     */
    public DestinationConfig createDestinationConfig() {
        return new DestinationConfig();
    }

    /**
     * Create an instance of {@link NamingProviderConfig }
     * 
     */
    public NamingProviderConfig createNamingProviderConfig() {
        return new NamingProviderConfig();
    }

    /**
     * Create an instance of {@link RendererConfig }
     * 
     */
    public RendererConfig createRendererConfig() {
        return new RendererConfig();
    }

    /**
     * Create an instance of {@link NamingConfig }
     * 
     */
    public NamingConfig createNamingConfig() {
        return new NamingConfig();
    }

    /**
     * Create an instance of {@link QuickFIXConfig }
     * 
     */
    public QuickFIXConfig createQuickFIXConfig() {
        return new QuickFIXConfig();
    }

    /**
     * Create an instance of {@link SessionConfig }
     * 
     */
    public SessionConfig createSessionConfig() {
        return new SessionConfig();
    }

    /**
     * Create an instance of {@link FactoryConfig }
     * 
     */
    public FactoryConfig createFactoryConfig() {
        return new FactoryConfig();
    }

    /**
     * Create an instance of {@link ConnectionConfig }
     * 
     */
    public ConnectionConfig createConnectionConfig() {
        return new ConnectionConfig();
    }

    /**
     * Create an instance of {@link ClasspathGroupConfig }
     * 
     */
    public ClasspathGroupConfig createClasspathGroupConfig() {
        return new ClasspathGroupConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HermesConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "config")
    public JAXBElement<HermesConfig> createConfig(HermesConfig value) {
        return new JAXBElement<HermesConfig>(_Config_QNAME, HermesConfig.class, null, value);
    }

}
