//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.12 at 08:23:44 AM BST 
//


package hermes.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="textMessage" type="{}XMLTextMessage" minOccurs="0"/>
 *         &lt;element name="mapMessage" type="{}XMLMapMessage" minOccurs="0"/>
 *         &lt;element name="objectMessage" type="{}XMLObjectMessage" minOccurs="0"/>
 *         &lt;element name="bytesMessage" type="{}XMLBytesMessage" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="session" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", propOrder = {
    "textMessage",
    "mapMessage",
    "objectMessage",
    "bytesMessage"
})
public class Entry {

    protected XMLTextMessage textMessage;
    protected XMLMapMessage mapMessage;
    protected XMLObjectMessage objectMessage;
    protected XMLBytesMessage bytesMessage;
    @XmlAttribute(name = "user")
    protected String user;
    @XmlAttribute(name = "time")
    protected String time;
    @XmlAttribute(name = "session")
    protected String session;
    @XmlAttribute(name = "destination")
    protected String destination;
    @XmlAttribute(name = "type")
    protected Integer type;

    /**
     * Gets the value of the textMessage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLTextMessage }
     *     
     */
    public XMLTextMessage getTextMessage() {
        return textMessage;
    }

    /**
     * Sets the value of the textMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLTextMessage }
     *     
     */
    public void setTextMessage(XMLTextMessage value) {
        this.textMessage = value;
    }

    /**
     * Gets the value of the mapMessage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMapMessage }
     *     
     */
    public XMLMapMessage getMapMessage() {
        return mapMessage;
    }

    /**
     * Sets the value of the mapMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMapMessage }
     *     
     */
    public void setMapMessage(XMLMapMessage value) {
        this.mapMessage = value;
    }

    /**
     * Gets the value of the objectMessage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLObjectMessage }
     *     
     */
    public XMLObjectMessage getObjectMessage() {
        return objectMessage;
    }

    /**
     * Sets the value of the objectMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLObjectMessage }
     *     
     */
    public void setObjectMessage(XMLObjectMessage value) {
        this.objectMessage = value;
    }

    /**
     * Gets the value of the bytesMessage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLBytesMessage }
     *     
     */
    public XMLBytesMessage getBytesMessage() {
        return bytesMessage;
    }

    /**
     * Sets the value of the bytesMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLBytesMessage }
     *     
     */
    public void setBytesMessage(XMLBytesMessage value) {
        this.bytesMessage = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSession(String value) {
        this.session = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setType(Integer value) {
        this.type = value;
    }

}
