//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.23 at 04:28:52 PM BST 
//


package hermes.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerProperty" type="{}Property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="JMSCorrelationID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSDeliveryMode" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="JMSDestination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSExpiration" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="JMSMessageID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSPriority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="JMSRedelivered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="JMSReplyTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSReplyToDomain" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="JMSTimestamp" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="JMSType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromQueue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="codec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="loader" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLMessage", propOrder = {
    "headerProperty"
})
@XmlSeeAlso({
    XMLObjectMessage.class,
    XMLMapMessage.class,
    XMLBytesMessage.class,
    XMLTextMessage.class
})
public class XMLMessage {

    protected List<Property> headerProperty;
    @XmlAttribute(name = "JMSCorrelationID")
    protected String jmsCorrelationID;
    @XmlAttribute(name = "JMSDeliveryMode")
    protected Integer jmsDeliveryMode;
    @XmlAttribute(name = "JMSDestination")
    protected String jmsDestination;
    @XmlAttribute(name = "JMSExpiration")
    protected Long jmsExpiration;
    @XmlAttribute(name = "JMSMessageID")
    protected String jmsMessageID;
    @XmlAttribute(name = "JMSPriority")
    protected Integer jmsPriority;
    @XmlAttribute(name = "JMSRedelivered")
    protected Boolean jmsRedelivered;
    @XmlAttribute(name = "JMSReplyTo")
    protected String jmsReplyTo;
    @XmlAttribute(name = "JMSReplyToDomain")
    protected Integer jmsReplyToDomain;
    @XmlAttribute(name = "JMSTimestamp")
    protected Long jmsTimestamp;
    @XmlAttribute(name = "JMSType")
    protected String jmsType;
    @XmlAttribute
    protected Boolean fromQueue;
    @XmlAttribute
    protected String codec;
    @XmlAttribute
    protected String loader;

    /**
     * Gets the value of the headerProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getHeaderProperty() {
        if (headerProperty == null) {
            headerProperty = new ArrayList<Property>();
        }
        return this.headerProperty;
    }

    /**
     * Gets the value of the jmsCorrelationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMSCorrelationID() {
        return jmsCorrelationID;
    }

    /**
     * Sets the value of the jmsCorrelationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMSCorrelationID(String value) {
        this.jmsCorrelationID = value;
    }

    /**
     * Gets the value of the jmsDeliveryMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getJMSDeliveryMode() {
        if (jmsDeliveryMode == null) {
            return  2;
        } else {
            return jmsDeliveryMode;
        }
    }

    /**
     * Sets the value of the jmsDeliveryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJMSDeliveryMode(Integer value) {
        this.jmsDeliveryMode = value;
    }

    /**
     * Gets the value of the jmsDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMSDestination() {
        return jmsDestination;
    }

    /**
     * Sets the value of the jmsDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMSDestination(String value) {
        this.jmsDestination = value;
    }

    /**
     * Gets the value of the jmsExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJMSExpiration() {
        return jmsExpiration;
    }

    /**
     * Sets the value of the jmsExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJMSExpiration(Long value) {
        this.jmsExpiration = value;
    }

    /**
     * Gets the value of the jmsMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMSMessageID() {
        return jmsMessageID;
    }

    /**
     * Sets the value of the jmsMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMSMessageID(String value) {
        this.jmsMessageID = value;
    }

    /**
     * Gets the value of the jmsPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJMSPriority() {
        return jmsPriority;
    }

    /**
     * Sets the value of the jmsPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJMSPriority(Integer value) {
        this.jmsPriority = value;
    }

    /**
     * Gets the value of the jmsRedelivered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isJMSRedelivered() {
        if (jmsRedelivered == null) {
            return false;
        } else {
            return jmsRedelivered;
        }
    }

    /**
     * Sets the value of the jmsRedelivered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJMSRedelivered(Boolean value) {
        this.jmsRedelivered = value;
    }

    /**
     * Gets the value of the jmsReplyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMSReplyTo() {
        return jmsReplyTo;
    }

    /**
     * Sets the value of the jmsReplyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMSReplyTo(String value) {
        this.jmsReplyTo = value;
    }

    /**
     * Gets the value of the jmsReplyToDomain property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJMSReplyToDomain() {
        return jmsReplyToDomain;
    }

    /**
     * Sets the value of the jmsReplyToDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJMSReplyToDomain(Integer value) {
        this.jmsReplyToDomain = value;
    }

    /**
     * Gets the value of the jmsTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJMSTimestamp() {
        return jmsTimestamp;
    }

    /**
     * Sets the value of the jmsTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJMSTimestamp(Long value) {
        this.jmsTimestamp = value;
    }

    /**
     * Gets the value of the jmsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMSType() {
        return jmsType;
    }

    /**
     * Sets the value of the jmsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMSType(String value) {
        this.jmsType = value;
    }

    /**
     * Gets the value of the fromQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFromQueue() {
        if (fromQueue == null) {
            return true;
        } else {
            return fromQueue;
        }
    }

    /**
     * Sets the value of the fromQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFromQueue(Boolean value) {
        this.fromQueue = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodec(String value) {
        this.codec = value;
    }

    /**
     * Gets the value of the loader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoader() {
        return loader;
    }

    /**
     * Sets the value of the loader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoader(String value) {
        this.loader = value;
    }

}
