//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.20 at 01:38:49 BST 
//


package hermes.xml;


/**
 * Java content class for XMLMessage complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/work/Workspaces/Hermes/Hermes/src/xml/jms2xml-schema.xsd line 11)
 * <p>
 * <pre>
 * &lt;complexType name="XMLMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerProperty" type="{}Property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="JMSCorrelationID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSDeliveryMode" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="JMSDestination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSExpiration" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="JMSMessageID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSPriority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="JMSRedelivered" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="JMSReplyTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JMSReplyToDomain" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="JMSTimestamp" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="JMSType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="loader" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XMLMessage {


    /**
     * Gets the value of the jmsTimestamp property.
     * 
     */
    long getJMSTimestamp();

    /**
     * Sets the value of the jmsTimestamp property.
     * 
     */
    void setJMSTimestamp(long value);

    /**
     * Gets the value of the HeaderProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the HeaderProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link hermes.xml.Property}
     * 
     */
    java.util.List getHeaderProperty();

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCodec();

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCodec(java.lang.String value);

    /**
     * Gets the value of the loader property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getLoader();

    /**
     * Sets the value of the loader property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setLoader(java.lang.String value);

    /**
     * Gets the value of the jmsType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getJMSType();

    /**
     * Sets the value of the jmsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setJMSType(java.lang.String value);

    /**
     * Gets the value of the jmsReplyTo property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getJMSReplyTo();

    /**
     * Sets the value of the jmsReplyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setJMSReplyTo(java.lang.String value);

    /**
     * Gets the value of the jmsDestination property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getJMSDestination();

    /**
     * Sets the value of the jmsDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setJMSDestination(java.lang.String value);

    /**
     * Gets the value of the jmsRedelivered property.
     * 
     */
    boolean isJMSRedelivered();

    /**
     * Sets the value of the jmsRedelivered property.
     * 
     */
    void setJMSRedelivered(boolean value);

    /**
     * Gets the value of the jmsExpiration property.
     * 
     */
    long getJMSExpiration();

    /**
     * Sets the value of the jmsExpiration property.
     * 
     */
    void setJMSExpiration(long value);

    /**
     * Gets the value of the jmsReplyToDomain property.
     * 
     */
    int getJMSReplyToDomain();

    /**
     * Sets the value of the jmsReplyToDomain property.
     * 
     */
    void setJMSReplyToDomain(int value);

    /**
     * Gets the value of the jmsDeliveryMode property.
     * 
     */
    int getJMSDeliveryMode();

    /**
     * Sets the value of the jmsDeliveryMode property.
     * 
     */
    void setJMSDeliveryMode(int value);

    /**
     * Gets the value of the jmsMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getJMSMessageID();

    /**
     * Sets the value of the jmsMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setJMSMessageID(java.lang.String value);

    /**
     * Gets the value of the jmsCorrelationID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getJMSCorrelationID();

    /**
     * Sets the value of the jmsCorrelationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setJMSCorrelationID(java.lang.String value);

    /**
     * Gets the value of the jmsPriority property.
     * 
     */
    int getJMSPriority();

    /**
     * Sets the value of the jmsPriority property.
     * 
     */
    void setJMSPriority(int value);

}
