//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.20 at 01:38:49 BST 
//


package hermes.xml;


/**
 * Java content class for XMLMapMessage complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/work/Workspaces/Hermes/Hermes/src/xml/jms2xml-schema.xsd line 62)
 * <p>
 * <pre>
 * &lt;complexType name="XMLMapMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{}XMLMessage">
 *       &lt;sequence>
 *         &lt;element name="bodyProperty" type="{}Property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XMLMapMessage
    extends hermes.xml.XMLMessage
{


    /**
     * Gets the value of the BodyProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the BodyProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBodyProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link hermes.xml.Property}
     * 
     */
    java.util.List getBodyProperty();

}
